POST http://localhost:5000/search/preferences
Content-Type: application/json

{
    "author": "Jean",
    "tags": [{"title": "science"}, {"title": "pop"}],
    "rating": "3",
    "createdAt": "2020-09-27"
}
###
